### ISSUE TITLE
Attempt to index local 'icons_by_filename' (a nil value)

### ISSUE THREAD

**Issue by fnune** [Ramilito/winbar.nvim#4] opened 2024-07-02 07:07 UTC
```
Error detected while processing DiagnosticChanged Autocommands for "*":
Error executing lua callback: .../.local/share/nvim/lazy/winbar.nvim/lua/winbar/utils.lua:105: attempt to index local 'icons_by_filename' (a nil value)
stack traceback:
        .../.local/share/nvim/lazy/winbar.nvim/lua/winbar/utils.lua:105: in function 'get_icon'
        ...o/.local/share/nvim/lazy/winbar.nvim/lua/winbar/init.lua:46: in function 'get_winbar'
        ...o/.local/share/nvim/lazy/winbar.nvim/lua/winbar/init.lua:104: in function <...o/.local/share/nvim/lazy/winbar.nvim/lua/winbar/init.lua:94>
        [C]: in function 'nvim_exec_autocmds'
        ...wrapped-0.10.0/share/nvim/runtime/lua/vim/diagnostic.lua:1033: in function 'set'
        ...ped-0.10.0/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:260: in function 'handle_diagnostics'
        ...ped-0.10.0/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:293: in function 'handler'
        ...wrapped-0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:1005: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

Right after loading `winbar.nvim`.

Lazy.nvim setup:

```lua
return {
  "Ramilito/winbar.nvim",
  event = "VimEnter",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  opts = {},
}
```

**Comment by Ramilito** [comment] 2024-07-02 07:34
Nice catch and thank you for reporting it! 🙏 
I've pushed a fix (this was caused by incorrect table lookup) into main so if you trigger an update it should work!

**Closed by Ramilito** 2024-07-02 07:34 UTC
